// IPC channels — esportati in shared per evitare che il preload importi
// l'intero ipcs/index.ts (che pulls in puppeteer, logger, ecc.) col rischio
// di triggerare `app.getPath` a module load nel preload context dove app
// non è disponibile.

export const IPC_CHANNELS = {
  EXPORT_ITEMS: 'EXPORT_ITEMS',
  IMPORT_ITEMS: 'IMPORT_ITEMS',
  PUPPETEER_OPEN_LOGIN_PAGE: 'PUPPETEER_OPEN_LOGIN_PAGE',
  PUPPETEER_STORE_COOKIES: 'PUPPETEER_STORE_COOKIES',
  GET_SETTINGS: 'GET_SETTINGS',
  STORE_SETTINGS: 'STORE_SETTINGS',
  GET_ITEMS: 'GET_ITEMS',
  GET_ITEM: 'GET_ITEM',
  INSERT_ITEMS: 'INSERT_ITEMS',
  UPDATE_ITEM: 'UPDATE_ITEM',
  CLONE_ITEM: 'CLONE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  REMOVE_LISTINGS: 'REMOVE_LISTINGS',
  GET_COOKIES: 'GET_COOKIES',
  FETCH_VEHICLE_CONFIG: 'FETCH_VEHICLE_CONFIG',
  GET_ANTHROPIC_KEY: 'GET_ANTHROPIC_KEY',
  GENERATE_DESCRIPTION: 'GENERATE_DESCRIPTION',
  GET_SCHEDULES: 'GET_SCHEDULES',
  SAVE_SCHEDULE: 'SAVE_SCHEDULE',
  DELETE_SCHEDULE: 'DELETE_SCHEDULE',
  CHECK_ITEMS_STATUS: 'CHECK_ITEMS_STATUS',
  FETCH_PRICE_RANGE: 'FETCH_PRICE_RANGE',
  OPEN_EXTERNAL: 'OPEN_EXTERNAL',
  FETCH_ITEMS_STATS: 'FETCH_ITEMS_STATS',
  UPDATE_SCHEDULE: 'UPDATE_SCHEDULE',
  GET_TRASH: 'GET_TRASH',
  RESTORE_ITEM: 'RESTORE_ITEM',
  PERMANENTLY_DELETE_ITEM: 'PERMANENTLY_DELETE_ITEM',
  EXTRACT_PRODUCT_INFO: 'EXTRACT_PRODUCT_INFO',
  SEARCH_EAN_BY_TITLE: 'SEARCH_EAN_BY_TITLE',
  LOOKUP_EAN_PRODUCT: 'LOOKUP_EAN_PRODUCT',
  RUN_SCHEDULE_NOW: 'RUN_SCHEDULE_NOW',
  CANCEL_OPERATION: 'CANCEL_OPERATION',
  IS_BUSY: 'IS_BUSY'
};
